name: analyse
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiohappyeyeballs=2.4.3=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h4cb3324_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - brotli-python=1.0.9=py38hd3f51b4_8
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.2.25=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - cffi=1.17.0=py38h4cb3324_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.1.1=py38hb1fd069_1
  - cpython=3.8.20=py38hd8ed1ab_2
  - cryptography=43.0.0=py38hb304008_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.8.5=py38h2698bfa_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deprecated=1.2.15=pyhff2d567_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - fonttools=4.53.1=py38h4cb3324_0
  - freetype=2.12.1=hdaf720e_2
  - frozenlist=1.4.1=py38h91455d4_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - glib=2.84.2=h232b036_0
  - glib-tools=2.84.2=h08ed4da_0
  - gst-plugins-base=1.18.5=h9e645db_0
  - gstreamer=1.18.5=hd78058f_0
  - h2=4.1.0=pyhd8ed1ab_0
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=58.2=ha925a31_3
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=8.5.0=pyha770c72_0
  - importlib-resources=6.4.5=pyhd8ed1ab_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.12.2=pyh08f2357_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh5737063_1
  - kiwisolver=1.4.5=py38hb1fd069_1
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=4.0.0=h63175ca_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libblas=3.9.0=25_win64_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=25_win64_mkl
  - libclang=12.0.0=default_h627e005_2
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.12.1=h9da9810_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.2=h8ffe710_5
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.84.2=h405b238_0
  - libhwloc=2.11.1=default_h8125262_1000
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - liblapack=3.9.0=25_win64_mkl
  - libogg=1.3.5=h2466b09_0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.47.0=h2466b09_1
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=h44ae7cf_1
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.13.8=h866ff63_0
  - libzlib=1.2.13=h2466b09_6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.7.3=py38h2724991_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mkl=2024.2.2=h66d3029_14
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.5=py38h91455d4_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - numpy=1.24.4=py38h1d91fd2_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openpyxl=3.1.5=py38h91455d4_0
  - openssl=3.4.1=ha4e3fda_0
  - packaging=24.2=pyhff2d567_1
  - pandas=2.0.3=py38hf08cf0d_1
  - parso=0.8.4=pyhd8ed1ab_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=py_1003
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.3.1=pyh8b19718_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_2
  - proj=9.2.0=heca977f_0
  - prompt-toolkit=3.0.48=pyha770c72_0
  - prompt_toolkit=3.0.48=hd8ed1ab_0
  - psutil=6.0.0=py38h4cb3324_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=h2466b09_4
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pygithub=2.6.1=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py38hbc1c497_3
  - pypdf2=3.0.1=pyhd8ed1ab_0
  - pyproj=3.5.0=py38h24c0b3c_1
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pysocks=1.7.1=pyh0701188_6
  - pytesseract=0.3.13=pyhd8ed1ab_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytz=2024.2=pyhd8ed1ab_0
  - pywin32=306=py38hd3f51b4_2
  - pyzmq=26.2.0=py38h3c56b06_0
  - qt-main=5.15.2=he8e5bd7_7
  - requests=2.32.3=pyhd8ed1ab_0
  - setuptools=75.3.0=pyhd8ed1ab_0
  - sip=6.7.12=py38hd3f51b4_0
  - six=1.16.0=pyh6c4a22f_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlite=3.47.0=h2466b09_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tbb=2021.13.0=hc790b64_0
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.2=pyhd8ed1ab_0
  - tornado=6.4.1=py38h4cb3324_0
  - tqdm=4.67.1=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_1
  - unicodedata2=15.1.0=py38h91455d4_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - vc=14.42=haa95532_5
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - wrapt=1.16.0=py38h91455d4_0
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.6.4=h4754444_1
  - yarl=1.9.4=py38h91455d4_0
  - zeromq=4.3.5=he1f189c_4
  - zipp=3.21.0=pyhd8ed1ab_0
  - zlib=1.2.13=h2466b09_6
  - zstandard=0.23.0=py38hf92978b_0
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - blinker==1.8.2
      - click==8.1.7
      - dash==2.18.2
      - dash-bootstrap-components==1.6.0
      - dash-colorscales==0.0.4
      - dash-core-components==2.0.0
      - dash-daq==0.5.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dtale==3.16.1
      - exceptiongroup==1.2.2
      - flask==3.0.3
      - flask-compress==1.15
      - future==1.0.0
      - h11==0.14.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - joblib==1.4.2
      - kaleido==0.2.1
      - keyboard==0.13.5
      - lz4==4.3.3
      - markupsafe==2.1.5
      - matplotlib==3.7.2
      - missingno==0.5.2
      - mouseinfo==0.1.3
      - networkx==3.1
      - outcome==1.3.0.post0
      - patsy==1.0.1
      - plotly==5.24.1
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pyjstat==2.4.0
      - pymsgbox==1.0.9
      - pyparsing==3.0.9
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==1.0.1
      - pytweening==1.2.0
      - retrying==1.3.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - selenium==4.27.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - squarify==0.4.4
      - statsmodels==0.14.1
      - strsimpy==0.2.1
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - trio==0.27.0
      - trio-websocket==0.11.1
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - werkzeug==3.0.6
      - wsproto==1.2.0
      - xarray==2023.1.0
variables:
  PYTHONPATH: D:\Scripts\analyse\Telemark\Python
  TEMP_FOLDER: D:\Scripts\analyse\Telemark\Python\Temp
  LOG_FOLDER: D:\Scripts\analyse\Telemark\Python\Log
prefix: C:\Users\_eve1509\AppData\Local\anaconda3\envs\analyse
