name: analyse
channels:
  - anaconda
  - conda-forge
  - esri
  - defaults
dependencies:
  - aiohappyeyeballs=2.4.0=py38haa95532_0
  - aiohttp=3.10.5=py38h827c3e9_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arcgis=2.1.0.5=py38_13
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-timeout=4.0.3=py38haa95532_0
  - attrs=24.2.0=py38haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.3=py38haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blinker=1.6.2=py38haa95532_0
  - bokeh=3.1.0=py38hd4e2768_0
  - bottleneck=1.3.5=py38h080aedc_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - brotli-python=1.0.9=py38hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - cachetools=5.3.3=py38haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - cffi=1.17.1=py38h827c3e9_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py38haa95532_0
  - cloudpickle=3.0.0=py38haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - comm=0.2.1=py38haa95532_0
  - contourpy=1.0.5=py38h59b6b97_0
  - cryptography=43.0.0=py38h89fc84f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.2=py38h2bbff1b_0
  - dask=2.12.0=py_0
  - dask-core=2.12.0=py_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - debugpy=1.6.7=py38hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - deprecated=1.2.13=py38haa95532_0
  - distributed=2.12.0=py38_0
  - et_xmlfile=1.1.0=py38haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.51.0=py38h2bbff1b_0
  - freetype=2.12.1=ha860e81_0
  - frozenlist=1.4.0=py38h2bbff1b_0
  - fsspec=2024.6.1=py38haa95532_0
  - geomet=1.0.0=py_0
  - gettext=0.22.5=h5728263_3
  - gettext-tools=0.22.5=h5a7288d_3
  - giflib=5.2.2=h7edc060_0
  - glib=2.78.4=hd77b12b_0
  - glib-tools=2.78.4=hd77b12b_0
  - gst-plugins-base=1.22.9=h001b923_1
  - gstreamer=1.22.9=hb4038d2_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=70.1=h0e60522_0
  - idna=3.7=py38haa95532_0
  - importlib-metadata=7.0.1=py38haa95532_0
  - importlib-resources=6.4.0=pyhd3eb1b0_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py38haa95532_0
  - ipython=8.12.2=py38haa95532_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.8.1=py38haa95532_0
  - jaraco.classes=3.2.1=pyhd3eb1b0_0
  - jedi=0.19.1=py38haa95532_0
  - jinja2=3.1.4=py38haa95532_0
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.23.0=py38haa95532_0
  - jsonschema-specifications=2023.7.1=py38haa95532_0
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=5.7.2=py38haa95532_0
  - jupyterlab_pygments=0.2.2=py38haa95532_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=24.3.1=py38haa95532_0
  - kiwisolver=1.4.4=py38hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.12=h83e58a3_0
  - lerc=3.0=hd77b12b_0
  - libasprintf=0.22.5=h5728263_3
  - libasprintf-devel=0.22.5=h5728263_3
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libclang=15.0.7=default_h3a3e6c3_5
  - libclang13=15.0.7=default_hf64faad_5
  - libcurl=8.12.0=h9da9810_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libgettextpo=0.22.5=h5728263_3
  - libgettextpo-devel=0.22.5=h5728263_3
  - libglib=2.78.4=ha17d25a_0
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.0=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.47.0=h2466b09_1
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=hd77b12b_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.5=h24da03e_0
  - libxslt=1.1.41=h0739af5_0
  - libzlib=1.2.13=h2466b09_6
  - locket=1.0.0=py38haa95532_0
  - lxml=5.2.1=py38h395c83e_1
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.6=py38haa95532_0
  - mistune=2.0.4=py38haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - more-itertools=10.3.0=py38haa95532_0
  - msgpack-python=1.0.3=py38h59b6b97_0
  - multidict=6.0.4=py38h2bbff1b_0
  - nbclient=0.8.0=py38haa95532_0
  - nbconvert=7.16.4=py38haa95532_0
  - nbformat=5.10.4=py38haa95532_0
  - nest-asyncio=1.6.0=py38haa95532_0
  - notebook=6.4.12=py_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - oauthlib=3.2.2=py38haa95532_0
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py38h827c3e9_0
  - openssl=3.4.0=h2466b09_0
  - packaging=24.1=py38haa95532_0
  - pandas=1.5.2=py38hf11a4ad_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py38haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.3.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=py38haa95532_1
  - platformdirs=3.10.0=py38haa95532_0
  - ply=3.11=py38_0
  - proj=8.2.1=h5ed7ab8_0
  - prometheus_client=0.14.1=py38haa95532_0
  - prompt-toolkit=3.0.43=py38haa95532_0
  - psutil=5.9.0=py38h2bbff1b_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygithub=2.5.0=pyhd8ed1ab_0
  - pygments=2.15.1=py38haa95532_1
  - pyjwt=2.8.0=py38haa95532_0
  - pynacl=1.5.0=py38h8cc25b3_0
  - pyopenssl=24.2.1=py38haa95532_0
  - pyparsing=3.1.2=py38haa95532_0
  - pypdf2=3.0.1=pyhd8ed1ab_0
  - pyproj=3.4.1=py38hb622704_0
  - pyqt=5.15.10=py38hd77b12b_0
  - pyqt5-sip=12.13.0=py38h2bbff1b_0
  - pyshp=2.3.1=py38haa95532_0
  - pysocks=1.7.1=py38haa95532_0
  - pyspnego=0.9.2=py38h2bbff1b_1
  - python=3.8.19=h4de0772_0_cpython
  - python-certifi-win32=1.6=py_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - python-dotenv=1.0.1=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.2=py38haa95532_0
  - python-gssapi=1.8.3=py38h2bbff1b_0
  - python-lmdb=1.4.1=py38hd77b12b_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.8=5_cp38
  - pytz=2024.1=py38haa95532_0
  - pywin32=305=py38h2bbff1b_0
  - pywin32-ctypes=0.2.2=py38haa95532_0
  - pywin32-security=302=py38_1
  - pywinpty=2.0.10=py38h5da7b33_0
  - pyyaml=6.0.2=py38h827c3e9_0
  - pyzmq=25.1.2=py38hd77b12b_0
  - qt-main=5.15.8=h720456b_6
  - referencing=0.30.2=py38haa95532_0
  - requests=2.31.0=py38haa95532_1
  - requests-gssapi=1.2.3=py_2
  - requests-kerberos=0.14.0=pyhd3eb1b0_0
  - requests-negotiate-sspi=0.5.3=py38_0
  - requests-oauthlib=2.0.0=py38haa95532_0
  - requests-toolbelt=1.0.0=py38haa95532_0
  - rpds-py=0.10.6=py38h062c2fa_0
  - ruamel.yaml=0.18.6=py38h827c3e9_0
  - ruamel.yaml.clib=0.2.8=py38h827c3e9_0
  - send2trash=1.8.2=py38haa95532_0
  - setuptools=75.1.0=py38haa95532_0
  - sip=6.7.12=py38hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.5=py38haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=h59b6b97_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - terminado=0.17.1=py38haa95532_0
  - tinycss2=1.2.1=py38haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tomli=2.0.1=py38haa95532_0
  - toolz=0.12.0=py38haa95532_0
  - tornado=6.4.1=py38h827c3e9_0
  - tqdm=4.66.5=py38h9909e9c_0
  - traitlets=5.14.3=py38haa95532_0
  - typing-extensions=4.11.0=py38haa95532_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=h57928b3_1
  - ujson=5.10.0=py38h5da7b33_0
  - unicodedata2=15.1.0=py38h2bbff1b_0
  - urllib3=1.26.19=py38haa95532_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.44.0=py38haa95532_0
  - widgetsnbextension=3.6.6=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38haa95532_2
  - winkerberos=0.9.1=py38h2bbff1b_0
  - winpty=0.4.3=4
  - wrapt=1.14.1=py38h2bbff1b_0
  - xlrd=2.0.1=pyhd3eb1b0_1
  - xyzservices=2022.9.0=py38haa95532_1
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - yarl=1.11.0=py38h827c3e9_0
  - zeromq=4.3.5=hd77b12b_0
  - zict=3.0.0=py38haa95532_0
  - zipp=3.20.2=py38haa95532_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - dash==2.17.1
      - dash-bootstrap-components==1.3.1
      - dash-colorscales==0.0.4
      - dash-core-components==2.0.0
      - dash-daq==0.5.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dtale==3.15.1
      - exceptiongroup==1.2.2
      - flask==2.2.5
      - flask-compress==1.15
      - flask-ngrok==0.0.25
      - future==1.0.0
      - h11==0.14.0
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - kaleido==0.2.1
      - keyboard==0.13.5
      - lz4==4.3.3
      - markupsafe==2.1.5
      - matplotlib==3.7.2
      - missingno==0.5.2
      - mouseinfo==0.1.3
      - networkx==3.1
      - outcome==1.3.0.post0
      - patsy==0.5.6
      - plotly==5.23.0
      - pyautogui==0.9.54
      - pygetwindow==0.0.9
      - pyjstat==2.4.0
      - pymsgbox==1.0.9
      - pyperclip==1.9.0
      - pyrect==0.2.0
      - pyscreeze==0.1.30
      - pytesseract==0.3.13
      - pytweening==1.2.0
      - retrying==1.3.4
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - screeninfo==0.8.1
      - seaborn==0.13.2
      - selenium==4.26.1
      - sniffio==1.3.1
      - squarify==0.4.4
      - statsmodels==0.14.1
      - strsimpy==0.2.1
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - trio==0.26.2
      - trio-websocket==0.11.1
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - wsproto==1.2.0
      - xarray==2023.1.0
      - zstandard==0.23.0
variables:
  PYTHONPATH: C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python
  TEMP_FOLDER: C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Temp
  LOG_FOLDER: C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Log
prefix: C:\Users\eve1509\.conda\envs\analyse
